[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "lazytables"
version = "0.0.2"
python_requires = ">=3.10"
description = "A micro-framework for managing data sources."
authors = [
    {name = "Ryan Young", email = "dev@ryayoung.com"}
]
readme = "README.md"
license = "MIT"
homepage = "https://github.com/ryayoung/lazytables"
repository = "https://github.com/ryayoung/lazytables"
documentation = "https://lazytables.readthedocs.io"
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3.11",
    "Topic :: Software Development :: Libraries"
]

# [project.urls]
# Bug Tracker = "https://github.com/ryayoung/lazytables/issues"

# [project.scripts]
# Uncomment and modify the lines below to create command-line scripts
# that call specific functions in your package
# my-script = "lazytables:my_function"

# [project.dependencies]
# Add your package's dependencies here
# pandas = "^1.3.3"

# [project.dev-dependencies]
# Add your package's development dependencies here
# pytest = "^6.2.5"

# [project.extras]
# Uncomment and modify the lines below to define optional features and their dependencies
# [project.extras.feature_name]
# some_dependency = "^1.0.0"
